name: CI

on: [push]

jobs:
  build:
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    name: ${{ matrix.os }}-${{ matrix.luaversion }}
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    # Workaround for https://github.com/actions/virtual-environments/issues/10
    - name: Avoid to use GitHub Actions-installed boost
      shell: bash
      run: |
        echo "::set-env name=BOOST_ROOT::"
    - name: Linux; install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install git clang cmake make gcc g++ libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev p7zip
        sudo apt-get install mysql-server default-libmysqlclient-dev libmysqlclient-dev libmysql++-dev
    - name: MacOS; install dependencies
      if: matrix.os == 'macOS-latest'
      run: |
        brew uninstall mysql
        brew install mysql
    - name: build & install
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install
        cmake --build . --config Debug --parallel 2
        cmake --install . --config Debug
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.14
