name: CI

on: [push]

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set BOOST_ROOT
      shell: bash
      run: |
        echo "::set-env name=BOOST_ROOT::$BOOST_ROOT_1_72_0"
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install git clang cmake make gcc g++ libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev p7zip
        sudo apt-get install mysql-server default-libmysqlclient-dev libmysqlclient-dev libmysql++-dev
    - name: Install dependencies
      shell: bash
      run: |
        echo $PATH
        echo $BOOST_ROOT
        echo $BOOST_ROOT_1_67_0
        echo $BOOST_LIBRARYDIR
        echo $Boost_NO_SYSTEM_PATHS
        echo $BOOST_INCLUDEDIR
        echo $BOOSTROOT
        echo $Boost_DIR
        echo foo
        ls -lah $BOOST_ROOT
        
    - name: Build & install
      run: |
        mkdir build
        cd build
        cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install
        cmake --build . --config Debug --parallel 2
        cmake --install . --config Debug

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # env:
      # Set boost root to choco installed path
      #BOOST_ROOT: C:\local\boost_1_67_0
      #BOOST_ROOT_1_67_0: C:\local\boost_1_67_0
      #BOOST_LIBRARYDIR: C:\local\boost_1_67_0\lib64-msvc-14.1\
      #Boost_NO_SYSTEM_PATHS: ON
    steps:
    - uses: actions/checkout@v2
    - name: Set BOOST_ROOT
      shell: bash
      run: |
        echo "::set-env name=BOOST_ROOT::$BOOST_ROOT_1_72_0"
    - name: Install dependencies
      shell: bash
      run: |
        echo $PATH
        echo $BOOST_ROOT
        echo $BOOST_ROOT_1_67_0
        echo $BOOST_LIBRARYDIR
        echo $Boost_NO_SYSTEM_PATHS
        echo $BOOST_INCLUDEDIR
        echo $BOOSTROOT
        echo $Boost_DIR
        echo foo
        ls -lah $BOOST_ROOT
    # install boost with choco due to https://github.com/actions/virtual-environments/issues/370
    - name: Install dependencies
      run: |
        # boost-msvc-14.1
        choco install --no-progress openssl
    - name: Configure
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ../ -DBoost_NO_BOOST_CMAKE=1 -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install
    - name: Build
      run: |
        cmake --build build --config Debug --parallel 2
    - name: Install
      run: |
        cmake --install build --config Debug
